openapi: 3.0.0
info:
  title: Book API
  description: A simple API to manage books
  version: "1.0.0"
paths:
  /books:
    get:
      summary: Get all books
      description: Fetch a list of all books in the library
      responses:
        200:
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string
                    publishedYear:
                      type: integer
    post:
      summary: Create a new book
      description: Add a new book to the library
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                publishedYear:
                  type: integer
      responses:
        201:
          description: Book created
  /books/{id}:
    get:
      summary: Get a book by ID
      description: Fetch a book by its unique ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Book details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  author:
                    type: string
                  publishedYear:
                    type: integer
        404:
          description: Book not found
    put:
      summary: Update a book by ID
      description: Update a book's details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                publishedYear:
                  type: integer
      responses:
        200:
          description: Book updated
        404:
          description: Book not found
    delete:
      summary: Delete a book by ID
      description: Delete a book from the library
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Book deleted
        404:
          description: Book not found
